[project]
name = "pyright-dataclass-protocol-issue"
version = "0.1.0"
description = ""
authors = [{ name = "Søren Gregersen", email = "sogr@ambu.com" }]
license = { text = "MIT" }
readme = "README.md"
requires-python = ">=3.10"

[tool.poetry]
package-mode = false

[tool.poetry.group.dev.dependencies]
pyright = "^1.1.400"

[tool.pyright]
strict = ["./**"]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
